# public kiritan data
train_align: downloads/kiritan_data/alignment/train
train_pitch: downloads/kiritan_data/pitch_beat_extraction/train
train_wav: downloads/kiritan_data/wav_info/train
val_align: downloads/kiritan_data/alignment/dev
val_pitch: downloads/kiritan_data/pitch_beat_extraction/dev
val_wav: downloads/kiritan_data/wav_info/dev

# standard: 4
# sing_quality: conf/sing_quality.csv


# feature related
sampling_rate: 22050
nfft: 2048
n_mels: 80
feat_dim: 1025
frame_length: 0.06
frame_shift: 0.03

# model related
model_save_dir: exp/10_16_Conformer_gnorm_useCNN_kernal7_linearUnits1024_numblock10/model                       # change
model_type: Conformer
normalize: True
# double_mel_loss: True
# perceptual_loss: 0.01

stats_file: exp/10_16_Conformer_gnorm_useCNN_kernal7_linearUnits1024_numblock10/model/feats_stats.npz           # change
stats_mel_file: exp/10_16_Conformer_gnorm_useCNN_kernal7_linearUnits1024_numblock10/model/feats_mel_stats.npz   # change

enc_attention_dim: 256
enc_attention_heads: 4
enc_linear_units: 1024
enc_num_blocks: 10
enc_dropout_rate: 0.1
enc_positional_dropout_rate: 0.1
enc_attention_dropout_rate: 0.0
enc_input_layer: "linear"

enc_normalize_before: True
enc_concat_after: False
enc_positionwise_layer_type: "linear"
enc_positionwise_conv_kernel_size: 1
enc_macaron_style: False
enc_pos_enc_layer_type: "rel_pos"
enc_selfattention_layer_type: "rel_selfattn"

enc_activation_type: "swish"
enc_use_cnn_module: True
enc_cnn_module_kernel: 7
enc_padding_idx: -1
dec_dropout: 0.1

embedding_size: 256                                                                 # change

dec_nhead: 4
dec_num_block: 6
num_frames: 500
char_max_len: 100
phone_size: 68
local_gaussian: False

# train related
resume: False
max_epochs: 300
gradclip: 5

batchsize: 10 # was 4
num_workers: 18 # was 10

accumulation_steps: 1
auto_select_gpu: False
gpu_id: 3

optimizer: "adam"
scheduler: "OneCycleLR"
noam_scale: 1.0
gradient_accumulation_steps: 1
noam_warmup_steps: 4000
train_step_log: 20
dev_step_log: 2
seed: 777
gpu: 1