# public kiritan data
train_align: /data5/jiatong/SVS_system/SVS/data/public_dataset/kiritan_data/alignment/train
train_pitch: /data5/jiatong/SVS_system/SVS/data/public_dataset/kiritan_data/pitch_beat_extraction/train
train_wav: /data5/jiatong/SVS_system/SVS/data/public_dataset/kiritan_data/wav_info/train
val_align: /data5/jiatong/SVS_system/SVS/data/public_dataset/kiritan_data/alignment/test
val_pitch: /data5/jiatong/SVS_system/SVS/data/public_dataset/kiritan_data/pitch_beat_extraction/test
val_wav: /data5/jiatong/SVS_system/SVS/data/public_dataset/kiritan_data/wav_info/test

# standard: 4
# sing_quality: conf/sing_quality.csv

model_type: LSTM
normalize: False # for utterence normalize
model_save_dir: exp/rnn_norm
normalize: True
double_mel_loss: False

batchsize: 10
num_workers: 0
accumulation_steps: 4
auto_select_gpu: False
gpu_id: 4

max_epochs: 250

resume: True
mask_free: False
use_asr_post: False
sampling_rate: 22050
nfft: 2048
feat_dim: 1025
n_mels: 80

frame_length: 0.06
frame_shift: 0.03

hidden_size: 512
embedding_size: 512
num_rnn_layers: 3
num_frames: 500
char_max_len: 100
optimizer: adam
lr: 0.001
phone_size: 68
seed: 777
gpu: 1

# train_step_log: 20
# dev_step_log: 2

# collect_stats: True
stats_file: exp/rnn_norm/feats_stats.npz
stats_mel_file: exp/rnn_norm/feats_mel_stats.npz
