# public kiritan data
train_align: data/alignment/train
train_pitch: data/pitch_beat_extraction/train
train_wav: data/wav_info/train
val_align: data/alignment/dev
val_pitch: data/pitch_beat_extraction/dev
val_wav: data/wav_info/dev

# standard: 4
# sing_quality: conf/sing_quality.csv

model_type: LSTM
# model_save_dir: exp/10_12_rnn_norm/model
# stats_file: exp/10_12_rnn_norm/model/feats_stats.npz
# stats_mel_file: exp/10_12_rnn_norm/model/feats_mel_stats.npz

normalize: True
double_mel_loss: False

batchsize: 10
num_workers: 6
accumulation_steps: 1
auto_select_gpu: False
gpu_id: 1

max_epochs: 150

resume: True
mask_free: False
use_asr_post: False
sampling_rate: 22050
nfft: 2048
feat_dim: 1025
n_mels: 80

frame_length: 0.06
frame_shift: 0.03

hidden_size: 256
embedding_size: 256
num_rnn_layers: 3
num_frames: 500
char_max_len: 100
optimizer: adam
lr: 0.001
phone_size: 68
seed: 666

train_step_log: 20
dev_step_log: 2

# collect_stats: True

