# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-ubuntu18
      - test-ubuntu20
      - test-centos7
      - test-debian9

jobs:
  test-ubuntu18:
    docker:
      - image: circleci/buildpack-deps:18.04
        environment:
          # default gcc version is 7
          SVS_PYTHON_VERSION: 3.8
          TH_VERSION: 1.7.1
          USE_CONDA: true
          # To avoid UnicodeEncodeError for python<=3.6
          LC_ALL: en_US.UTF-8
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt-get update -qq
            # NOTE(kamo): cmake libsndfile1-dev will be download using anacond:
            sudo apt-get install -qq -y bc
            sudo localedef -f UTF-8 -i en_US en_US
      - run:
          name: install SVS
          command: |
            ./ci/install.sh
      - run:
          name: test shell
          command: |
            ./ci/test_shell.sh
      - run:
          name: test python
          command: |
            ./ci/test_python.sh

  test-ubuntu20:
    docker:
      - image: circleci/buildpack-deps:20.04
        environment:
          # default gcc version is 9
          SVS_PYTHON_VERSION: 3.8
          TH_VERSION: 1.7.1
          USE_CONDA: true
          # To avoid UnicodeEncodeError for python<=3.6
          LC_ALL: en_US.UTF-8
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt-get update -qq
            # NOTE(kamo): cmake libsndfile1-dev will be download using anacond:
            sudo apt-get install -qq -y bc
            sudo localedef -f UTF-8 -i en_US en_US
      - run:
          name: install SVS
          command: |
            ./ci/install.sh
      - run:
          name: test shell
          command: |
            ./ci/test_shell.sh
      - run:
          name: test python
          command: |
            ./ci/test_python.sh

  test-centos7:
    docker:
      - image: centos:7
        environment:
          SVS_PYTHON_VERSION: 3.8
          TH_VERSION: 1.7.1
          USE_CONDA: true
          CC: /opt/rh/devtoolset-7/root/usr/bin/gcc
          CXX: /opt/rh/devtoolset-7/root/usr/bin/g++
          # To avoid UnicodeEncodeError for python<=3.6
          LC_ALL: en_US.UTF-8
    working_directory: ~/repo

    steps:
      - run:
          name: install dependencies
          command: |
            # NOTE(kamo): cmake sndfile will be download using anacond:
            yum install -y git centos-release-scl make bzip2 wget which unzip bc
            yum-config-manager --enable rhel-server-rhscl-7-rpms
            yum install -y devtoolset-7-gcc-c++
            localedef -f UTF-8 -i en_US en_US
      - checkout
      - run:
          name: install SVS
          command: |
            # NOTE(karita) this line exited 1
            # source scl_source enable devtoolset-7
            PATH="/opt/rh/devtoolset-7/root/usr/bin:${PATH:-}"
            ./ci/install.sh
      - run:
          name: test shell
          command: |
            PATH="/opt/rh/devtoolset-7/root/usr/bin:${PATH:-}"
            ./ci/test_shell.sh
      - run:
          name: test python
          command: |
            PATH="/opt/rh/devtoolset-7/root/usr/bin:${PATH:-}"
            ./ci/test_python.sh

  test-debian9:
    docker:
      - image: debian:9
        environment:
          SVS_PYTHON_VERSION: 3.8
          TH_VERSION: 1.7.1
          USE_CONDA: true
          CC: gcc-6
          CXX: g++-6
          # To avoid UnicodeEncodeError for python<=3.6
          LC_ALL: en_US.UTF-8
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apt-get update -qq
            # NOTE(kamo): cmake sndfile will be download using anacond:
            apt-get install -qq -y build-essential git g++-6 unzip bzip2 wget curl bc locales make
            localedef -f UTF-8 -i en_US en_US
      - run:
          name: install SVS
          command: |
            ./ci/install.sh
      - run:
          name: test shell
          command: |
            ./ci/test_shell.sh
      - run:
          name: test python
          command: |
            ./ci/test_python.sh
