train_align: /export/c04/jiatong/project/svs/SVS_system/data/alignment/other_set/
train_pitch: /export/c04/jiatong/project/svs/SVS_system/data/pitch_beat_extraction/other/
train_wav: /export/c04/jiatong/project/svs/SVS_system/data/wav_info/other
val_align: /export/c04/jiatong/project/svs/SVS_system/data/alignment/clean_set/
val_pitch: /export/c04/jiatong/project/svs/SVS_system/data/pitch_beat_extraction/clean/
val_wav: /export/c04/jiatong/project/svs/SVS_system/data/wav_info/clean
model_save_dir: exp/debug/model


sampling_rate: 44100
frame_length: 0.06
frame_shift: 0.03
model_type: GLU_Transformer
max_epochs: 100
gradclip: 5
batchsize: 4
num_workers: 10
hidden_size: 256
embedding_size: 256
glu_num_layers: 3
dec_nhead: 4
dec_num_block: 6
num_frames: 500
char_max_len: 100
optimizer: noam
noam_scale: 1.0
gradient_accumulation_steps: 1
noam_warmup_steps: 25000
phone_size: 68
seed: 777
gpu: 1
