# public kiritan data
train_align: downloads/kiritan_data/alignment/train
train_pitch: downloads/kiritan_data/pitch_beat_extraction/train
train_wav: downloads/kiritan_data/wav_info/train
val_align: downloads/kiritan_data/alignment/dev
val_pitch: downloads/kiritan_data/pitch_beat_extraction/dev
val_wav: downloads/kiritan_data/wav_info/dev

# standard: 4
# sing_quality: conf/sing_quality.csv


# feature related
sampling_rate: 22050
nfft: 2048
n_mels: 80
feat_dim: 1025
frame_length: 0.06
frame_shift: 0.03

# model related
model_save_dir: exp/10_15_GLU_gnorm/model
stats_file: exp/10_15_GLU_gnorm/model/feats_stats.npz
stats_mel_file: exp/10_15_GLU_gnorm/model/feats_mel_stats.npz

model_type: GLU_Transformer
normalize: True

hidden_size: 256
embedding_size: 256
glu_num_layers: 3
dec_nhead: 4
dec_num_block: 6
num_frames: 500
char_max_len: 100
phone_size: 68
local_gaussian: True

# train related
resume: True
max_epochs: 300
gradclip: 5

batchsize: 10
num_workers: 18
accumulation_steps: 1
auto_select_gpu: False
gpu_id: 1

optimizer: noam
noam_scale: 1.0
# gradient_accumulation_steps: 1
noam_warmup_steps: 4000
train_step_log: 20
dev_step_log: 2
seed: 777
gpu: 1
# normalize: True # for utterence normalize
# collect_stats: True

