# public kiritan data
train_align: downloads/kiritan_data/alignment/train
train_pitch: downloads/kiritan_data/pitch_beat_extraction/train
train_wav: downloads/kiritan_data/wav_info/train
val_align: downloads/kiritan_data/alignment/dev
val_pitch: downloads/kiritan_data/pitch_beat_extraction/dev
val_wav: downloads/kiritan_data/wav_info/dev

sampling_rate: 22050
nfft: 2048
feat_dim: 1025
frame_length: 0.06
frame_shift: 0.03

model_type: PureTransformer_norm
normalize: True
model_save_dir: exp/pure_transformer_norm/model

max_epochs: 100
gradclip: 5

batchsize: 8
num_workers: 0

accumulation_steps: 1
auto_select_gpu: False
gpu_id: 1

hidden_size: 256
embedding_size: 256
glu_num_layers: 3
dec_nhead: 4
dec_num_block: 6
num_frames: 500
char_max_len: 100
optimizer: noam
noam_scale: 1.0
gradient_accumulation_steps: 1
noam_warmup_steps: 5000
phone_size: 68
seed: 777
gpu: 1

# collect_stats: True
stats_file: exp/pure_transformer_norm/model/feats_stats.npz
stats_mel_file: exp/pure_transformer_norm/model/feats_mel_stats.npz
#initmodel: /home/yzhan/SVS_system/exp/debug1/model/epoch_3.pth.tar
# pretrain_encoder: /home/yzhan/SVS_system/exp/debug1/model/checkpoint_transformer_160000.pth.tar
