name: debian9

on: [push, pull_request]

jobs:
  check_skip:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
  linter_and_test:
    runs-on: ubuntu-latest
    container:
      image: debian:9
      env:
        SVS_PYTHON_VERSION: 3.8
        TH_VERSION: 1.7.1
        USE_CONDA: true
        CC: gcc-6
        CXX: g++-6
        # To avoid UnicodeEncodeError for python<=3.6
        LC_ALL: en_US.UTF-8
    needs: check_skip
    steps:
      - uses: actions/checkout@master
      - name: check OS
        run: cat /etc/os-release
      - name: install dependencies
        run: |
          apt-get update -qq
          # NOTE: cmake sndfile will be download using anacond:
          apt-get install -qq -y build-essential git g++-6 unzip bzip2 wget curl bc locales make
          localedef -f UTF-8 -i en_US en_US
      - name: install SVS
        run: ./ci/install.sh
      - name: test shell
        run: ./ci/test_shell.sh
      - name: test python
        run: ./ci/test_python.sh
