# public OFUTON_P_UTAGOE_DB data
train_align: data/alignment/train
train_pitch: data/pitch_beat_extraction/train
train_wav: data/wav_info/train
val_align: data/alignment/dev
val_pitch: data/pitch_beat_extraction/dev
val_wav: data/wav_info/dev

# standard: 4
# sing_quality: conf/sing_quality.csv

model_type: LSTM
model_save_dir: exp/2020_1_21_rnn_norm_perp/model
stats_file: exp/2020_1_21_rnn_norm_perp/model/feats_stats.npz
stats_mel_file: exp/2020_1_21_rnn_norm_perp/model/feats_mel_stats.npz

normalize: True
double_mel_loss: False
perceptual_loss: 0.01

accumulation_steps: 1
auto_select_gpu: True
gpu_id: 0

max_epochs: 300

batchsize: 10
num_workers: 5

resume: True
mask_free: False
use_asr_post: False
sampling_rate: 22050
nfft: 2048
feat_dim: 1025
n_mels: 80

frame_length: 0.06
frame_shift: 0.03

hidden_size: 256
embedding_size: 256
num_rnn_layers: 3
num_frames: 500
char_max_len: 100
optimizer: adam
lr: 0.001
phone_size: 68
seed: 777

train_step_log: 20
dev_step_log: 2

